name: ezcut
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - opencv
  - pillow
  - tqdm
  - requests
  - pip:
    - moviepy
    - pysrt
    - tkinter
    - whisper
    - faster-whisper